### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Nerdyvedi** [neatpun/real-time-background-replacement#1]
Hi,
Great work.

I am trying to test this model with my webcam, but am getting the following error:
 
  ` 
File "live_webcam.py", line 123, in segmentation
cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
^CException ignored in: <module 'threading' from '/Users/zomato/anaconda3/envs/tensorflow_env/lib/python3.7/threading.py'>`

Thank you

**Comment by neatpun** [comment]
I've made it compatible with both old and new versions of OpenCV. Does it work now?

**Comment by Nerdyvedi** [comment]
Yeah, It works now. Thanks
Do you have any ideas on how to improve it's quality? It runs at around 2 fps, Around 10fps is almost ideal for real time purposes.

**Comment by neatpun** [comment]
> 
> 
> Yeah, It works now. Thanks
> Do you have any ideas on how to improve it's quality? It runs at around 2 fps, Around 10fps is almost ideal for real time purposes.

From the fps, I'm guessing that you're running it on CPU. For real time purposes, you should run tensorflow on GPU.
